[functions]
directory = "function"
included_files = ["function/assets/*"]

[context.development.environment]
REACT_APP_GAME_URL = "https://k5pn0dzua9.execute-api.us-east-1.amazonaws.com/default/Spelbij-game-creator"
